### PR TITLE
Add support for clang-format

### LINKED ISSUE #69: Formatter configuration needed
As the project grows in developers, we will have more and more inconsistencies in formatting, making pull requests more difficult to review (see, e.g., https://github.com/precice/calculix-adapter/pull/68). So, let's add a formatter!

Adding a `.clang-format` is quite easy, but it needs some time to fine-tune it to a style that is close to the original/intented.

Examples:
- [preCICE](https://github.com/precice/precice/blob/develop/.clang-format)
- [OpenFOAM adapter](https://github.com/precice/openfoam-adapter/blob/develop/.clang-format) (with some comments on how we try to fit the OpenFOAM style guidelines) - see also https://github.com/precice/openfoam-adapter/pull/173
- [deal.II adapter](https://github.com/precice/dealii-adapter/blob/master/.clang-format)

If needed, I can prepare something to discuss.

### PR DESCRIPTION
**Pull request by MakisH**
We need some automatic formatting to maintain the history clean and understandable. 

This adds the following:
- A script `tools/format-code.sh`, which only formats the C and C++ files in `adapter/`. I am ignoring the CalculiX files, as I guess @KyleDavisSA needs to do some diff between CalculiX and the adapter whenever porting to new versions. I could still only enforce indentation, or go the full way and also format the CalculiX files.
- The same clang-format config as in preCICE. I guess some familiarity with the style helps.
- A GitHub Actions workflow to check the formatting (only of the files in `adapter/`).

Closes #69.

Note that merging this could cause some merge conflicts in already open merge requests.

### CODE REVIEW

**Comment by KyleDavisSA** [comment]
Do you think it would be better to merge this first, and fix any other merge issues it might cause, or wait until the others are merged?

**Comment by MakisH** [comment]
> Do you think it would be better to merge this first, and fix any other merge issues it might cause, or wait until the others are merged?

This is really easy to reapply, so I would wait for #73 first.

**Comment by MakisH** [comment]
I would actually wait until we merge the `v2.17` to `develop` first.

**Comment by MakisH** [comment]
Closing in favor of #83.

**Pull request closed without merging**
