### PR TITLE
2D simulations major overhaul

### PR DESCRIPTION
**Pull request by boris-martin**
# Context

Currently, simulations in Quasi2D-3D are limited to meshes where there is exactly 2 points in 3D space for a 2D point: one with z=0 and one with z=1. In particular, this forbids the use of 2nd order elements. Furthermore, mapping from 3D to 2D is always consistent but mapping from 2D to 3D is conservative. For instance, reading forces and sending displacements works but the opposite is broken. Having a Temperature Dirichlet BC is not possible (it would be divided by 2)

# Approach

Mapping is reworked to allow for a variable number of 3D points per 2D point. Both consistent and conservative mappings are implemented. Number of 3D points on a 2D point is used to compute average in a consistent write, or to split loads in conservate reads.
Code is refactored to limit the number of 2D-specific code inside `PreciceInterface.c` (which is 100 lines shorter!)

# New features

- Allows higher order meshes in 2D
- Allows actual 2D elements to be used (plane stress / plane strain as well as shells)
- Should fix reading displacements & temperatures

# Checks

- [ ] Perpendicular flap with 2nd order elements
- [x] Perpendicular flap with 2D plane stress elements: ~~done, but results inconsistent. Investigation ongoing.~~ Shell elements give good results, unlike the plane stress elements. Apparently 1st order Shell expands into C38DI whereas plane stress expand into C3D, which probably explains it. Anyway, 2D coupling with 2D elements works, in terms of code
- [x] Non-regression test for current perpendicular flap
- [x] Thermal simulation to check Temperature reading
- [x] Check for dead code to remove or forgotten cleanup

# Future work

- Some refactoring could be done for 3D coupling
- This only works for node mesh. Making stuff work on face meshes could be interesting.

### CODE REVIEW

**Comment by boris-martin** [comment]
Test case for temperature: https://github.com/boris-martin/ccx_heat_2d_test
It's a simple heat conduction in a cubic domain with one side at 300K and another side where Temperature is read from preCICE, with a simple script that always sends T = 350K.
It works in 3D or in 2D with this PR, but using this in 2D without the PR reads a temperature of 175K instead.

(On a side note, this is a case that spontanously reproduces issue #86, which I struggled to reproduce before. Life is weird that way)

**Review by IshaanDesai — APPROVED** [review]
This is a really significant improvement to the 2D-3D case handling capability and is a general and clean solution! Great work :+1: I did not look at each and every line of the change, but I ran the perpendicular-flap tutorial case with OpenFOAM and SU2 and the results are as expected.

**Comment by uekerman** [comment]
Hi @boris-martin 
Wouldn't your testcase already (almost) be a solution to https://github.com/precice/tutorials/issues/103 ?

**Comment by boris-martin** [comment]
@uekerman Exactly, I was trying to set up this case then realized all the missing features on the adapter and started this PR.
There are a few more things to work on. For instance 2D coupling works for nodal meshes but not meshes with face centers, required for heat fluxes. But this new tutorial case is a milestone I've set up :)
I'd also like to add the support for brick elements in CHT (only tetrahedra are supported yet) which is part of https://github.com/precice/calculix-adapter/pull/91 but wasn't yet adapted to 2D.................

**Pull request merged**
